/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    pages: Page;
    categories: Category;
    authors: Author;
    media: Media;
    redirects: Redirect;
    'contact-messages': ContactMessage;
    users: User;
    'audit-logs': AuditLog;
    'migration-runs': MigrationRun;
    'migration-issues': MigrationIssue;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'migration-runs': MigrationRunsSelect<false> | MigrationRunsSelect<true>;
    'migration-issues': MigrationIssuesSelect<false> | MigrationIssuesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    homepage: Homepage;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * Short summary for cards and search results
   */
  excerpt?: string | null;
  featuredImage?: (string | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  format: 'standard' | 'video' | 'audio' | 'ebook';
  video?: {
    url?: string | null;
    youtubeId?: string | null;
  };
  /**
   * Link to the hosted audio (https only). Audio uploads are not accepted.
   */
  audio?: {
    url?: string | null;
  };
  attachments?:
    | {
        file: string | Media;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Public URL: /<number>/. Assigned automatically.
   */
  postNumber?: number | null;
  publishedAt?: string | null;
  categories?: (string | Category)[] | null;
  /**
   * Defaults to the first category
   */
  primaryCategory?: (string | null) | Category;
  author?: (string | null) | Author;
  /**
   * Show in the homepage slider
   */
  featured?: boolean | null;
  readingMinutes?: number | null;
  flags?: {
    needsReview?: boolean | null;
    /**
     * Title was generated from the text (WordPress title was empty)
     */
    titleDerived?: boolean | null;
    /**
     * Publish date looked tampered/invalid in WordPress
     */
    dateSuspect?: boolean | null;
    reviewNote?: string | null;
  };
  createdBy?: (string | null) | User;
  searchText?: string | null;
  searchKey?: string | null;
  legacy?: {
    wpId?: number | null;
    legacySlugs?: string[] | null;
    legacyUrls?: string[] | null;
    /**
     * Hash of the sanitized source record (idempotent re-runs)
     */
    sourceHash?: string | null;
    migratedAt?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for screen readers. Required for images added by editors.
   */
  alt?: string | null;
  caption?: string | null;
  credit?: string | null;
  blurDataURL?: string | null;
  /**
   * SHA-256 of the original upload (dedupe)
   */
  sourceSha256?: string | null;
  security?: {
    kind?: string | null;
    reencoded?: boolean | null;
    scannedAt?: string | null;
  };
  legacy?: {
    wpId?: number | null;
    legacySlugs?: string[] | null;
    legacyUrls?: string[] | null;
    /**
     * Hash of the sanitized source record (idempotent re-runs)
     */
    sourceHash?: string | null;
    migratedAt?: string | null;
  };
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * URL segment. Normalised automatically (Malayalam-safe, no invisible characters).
   */
  slug: string;
  description?: string | null;
  image?: (string | null) | Media;
  /**
   * Lower numbers first
   */
  order?: number | null;
  /**
   * Placement-only category (e.g. the old "slider" flag): not listed publicly
   */
  hidden?: boolean | null;
  legacy?: {
    wpId?: number | null;
    legacySlugs?: string[] | null;
    /**
     * Hash of the sanitized source record (idempotent re-runs)
     */
    sourceHash?: string | null;
    migratedAt?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  name: string;
  /**
   * URL segment. Normalised automatically (Malayalam-safe, no invisible characters).
   */
  slug: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (string | null) | Media;
  legacy?: {
    wpId?: number | null;
    legacySlugs?: string[] | null;
    /**
     * Hash of the sanitized source record (idempotent re-runs)
     */
    sourceHash?: string | null;
    migratedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  /**
   * Admin: everything. Editor: all content + publishing. Author: own drafts only.
   */
  role: 'admin' | 'editor' | 'author';
  totpSecret?: string | null;
  hasTotp?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  kind: 'kb' | 'static';
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown as tabs (e.g. ഖുര്‍ആന്‍ സൂക്തങ്ങള്‍ / നബി വചനങ്ങള്‍)
   */
  sections?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (string | null) | Media;
  /**
   * URL segment. Normalised automatically (Malayalam-safe, no invisible characters).
   */
  slug: string;
  parent?: (string | null) | Page;
  /**
   * Computed from parent + slug
   */
  path?: string | null;
  order?: number | null;
  flags?: {
    needsReview?: boolean | null;
    /**
     * Title was generated from the text (WordPress title was empty)
     */
    titleDerived?: boolean | null;
    /**
     * Publish date looked tampered/invalid in WordPress
     */
    dateSuspect?: boolean | null;
    reviewNote?: string | null;
  };
  createdBy?: (string | null) | User;
  searchText?: string | null;
  searchKey?: string | null;
  legacy?: {
    wpId?: number | null;
    legacySlugs?: string[] | null;
    legacyUrls?: string[] | null;
    /**
     * Hash of the sanitized source record (idempotent re-runs)
     */
    sourceHash?: string | null;
    migratedAt?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * Old path, e.g. /some-old-slug/ (stored decoded, NFC)
   */
  from: string;
  to?: string | null;
  code: '301' | '308' | '410';
  source?: ('manual' | 'auto' | 'migration') | null;
  hits?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: string;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  status?: ('new' | 'read' | 'replied' | 'spam') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  action: 'create' | 'update' | 'delete' | 'login' | 'publish' | 'unpublish' | 'mfa-lockout';
  target: string;
  docId?: string | null;
  changed?: string | null;
  user?: (string | null) | User;
  /**
   * Non-user actor, e.g. migration run id
   */
  actor?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-runs".
 */
export interface MigrationRun {
  id: string;
  runId: string;
  status: 'running' | 'completed' | 'failed' | 'aborted';
  dryRun?: boolean | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  /**
   * Per-entity source / migrated / quarantined / rejected counts (JSON)
   */
  counts?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-issues".
 */
export interface MigrationIssue {
  id: string;
  run?: (string | null) | MigrationRun;
  entity: 'post' | 'page' | 'category' | 'author' | 'media' | 'menu' | 'redirect';
  wpId?: number | null;
  gate: 'A-source' | 'B-media' | 'C-content' | 'validation';
  severity: 'quarantined' | 'rejected' | 'warning';
  summary: string;
  /**
   * Defanged evidence only — never raw payloads (JSON)
   */
  details?: string | null;
  resolved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: string | ContactMessage;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'migration-runs';
        value: string | MigrationRun;
      } | null)
    | ({
        relationTo: 'migration-issues';
        value: string | MigrationIssue;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  format?: T;
  video?:
    | T
    | {
        url?: T;
        youtubeId?: T;
      };
  audio?:
    | T
    | {
        url?: T;
      };
  attachments?:
    | T
    | {
        file?: T;
        label?: T;
        id?: T;
      };
  postNumber?: T;
  publishedAt?: T;
  categories?: T;
  primaryCategory?: T;
  author?: T;
  featured?: T;
  readingMinutes?: T;
  flags?:
    | T
    | {
        needsReview?: T;
        titleDerived?: T;
        dateSuspect?: T;
        reviewNote?: T;
      };
  createdBy?: T;
  searchText?: T;
  searchKey?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        legacySlugs?: T;
        legacyUrls?: T;
        sourceHash?: T;
        migratedAt?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  intro?: T;
  content?: T;
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  featuredImage?: T;
  slug?: T;
  parent?: T;
  path?: T;
  order?: T;
  flags?:
    | T
    | {
        needsReview?: T;
        titleDerived?: T;
        dateSuspect?: T;
        reviewNote?: T;
      };
  createdBy?: T;
  searchText?: T;
  searchKey?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        legacySlugs?: T;
        legacyUrls?: T;
        sourceHash?: T;
        migratedAt?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  order?: T;
  hidden?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        legacySlugs?: T;
        sourceHash?: T;
        migratedAt?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  photo?: T;
  legacy?:
    | T
    | {
        wpId?: T;
        legacySlugs?: T;
        sourceHash?: T;
        migratedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  blurDataURL?: T;
  sourceSha256?: T;
  security?:
    | T
    | {
        kind?: T;
        reencoded?: T;
        scannedAt?: T;
      };
  legacy?:
    | T
    | {
        wpId?: T;
        legacySlugs?: T;
        legacyUrls?: T;
        sourceHash?: T;
        migratedAt?: T;
      };
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  code?: T;
  source?: T;
  hits?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  totpSecret?: T;
  hasTotp?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  target?: T;
  docId?: T;
  changed?: T;
  user?: T;
  actor?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-runs_select".
 */
export interface MigrationRunsSelect<T extends boolean = true> {
  runId?: T;
  status?: T;
  dryRun?: T;
  startedAt?: T;
  finishedAt?: T;
  counts?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-issues_select".
 */
export interface MigrationIssuesSelect<T extends boolean = true> {
  run?: T;
  entity?: T;
  wpId?: T;
  gate?: T;
  severity?: T;
  summary?: T;
  details?: T;
  resolved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  siteNameMl?: string | null;
  tagline?: string | null;
  /**
   * Main logo (left)
   */
  logo?: (string | null) | Media;
  /**
   * Partner logo (right), e.g. Dialogue Centre Kerala
   */
  partnerLogo?: (string | null) | Media;
  partnerUrl?: string | null;
  /**
   * Fallback social-share image (1200×630)
   */
  defaultOgImage?: (string | null) | Media;
  social?: {
    facebook?: string | null;
    x?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    whatsapp?: string | null;
    telegram?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Small links beside the logo on desktop and at the bottom of the mobile menu (e.g. About Us · Postal Library).
   */
  topBarLinks?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'none') | null;
          newTab?: boolean | null;
          label: string;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  showSocialInTopBar?: boolean | null;
  /**
   * Blue navigation bar. Up to three levels.
   */
  mainMenu?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'none') | null;
          newTab?: boolean | null;
          label: string;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
        };
        children?:
          | {
              link: {
                type?: ('reference' | 'custom' | 'none') | null;
                newTab?: boolean | null;
                label: string;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null)
                  | ({
                      relationTo: 'categories';
                      value: string | Category;
                    } | null);
                url?: string | null;
              };
              children?:
                | {
                    link: {
                      type?: ('reference' | 'custom' | 'none') | null;
                      newTab?: boolean | null;
                      label: string;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: string | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: string | Post;
                          } | null)
                        | ({
                            relationTo: 'categories';
                            value: string | Category;
                          } | null);
                      url?: string | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  /**
   * Main column, top to bottom
   */
  layout?:
    | (
        | FeaturedSliderBlock
        | CategoryFeatureBlock
        | CategoryGridBlock
        | CategoryListBlock
        | MediaShelfBlock
        | RichTextBlock
        | BannerBlock
      )[]
    | null;
  /**
   * Right sidebar on desktop; shown after the main column on mobile
   */
  sidebar?:
    | (CategoryListBlock | QuickLinksBlock | QuickContactBlock | FollowUsBlock | BannerBlock | RichTextBlock)[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedSliderBlock".
 */
export interface FeaturedSliderBlock {
  source?: ('featured' | 'category') | null;
  category?: (string | null) | Category;
  limit: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredSlider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryFeatureBlock".
 */
export interface CategoryFeatureBlock {
  width?: ('full' | 'half') | null;
  category: string | Category;
  /**
   * Section heading. Defaults to the category name.
   */
  title?: string | null;
  layout: 'split' | 'stacked';
  limit: number;
  showMoreLink?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryFeature';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock".
 */
export interface CategoryGridBlock {
  width?: ('full' | 'half') | null;
  category: string | Category;
  /**
   * Section heading. Defaults to the category name.
   */
  title?: string | null;
  columns: '2' | '3' | '4';
  limit: number;
  showMoreLink?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryListBlock".
 */
export interface CategoryListBlock {
  width?: ('full' | 'half') | null;
  category: string | Category;
  /**
   * Section heading. Defaults to the category name.
   */
  title?: string | null;
  limit: number;
  showThumbnails?: boolean | null;
  showMoreLink?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaShelfBlock".
 */
export interface MediaShelfBlock {
  width?: ('full' | 'half') | null;
  format: 'video' | 'audio' | 'ebook';
  /**
   * Optional: limit to one category
   */
  category?: (string | null) | Category;
  /**
   * Section heading. Defaults to the category name.
   */
  title?: string | null;
  limit: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaShelf';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  width?: ('full' | 'half') | null;
  /**
   * Section heading. Defaults to the category name.
   */
  title?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  width?: ('full' | 'half') | null;
  image: string | Media;
  link?: {
    type?: ('reference' | 'custom' | 'none') | null;
    newTab?: boolean | null;
    label?: string | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'categories';
          value: string | Category;
        } | null);
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuickLinksBlock".
 */
export interface QuickLinksBlock {
  /**
   * Section heading. Defaults to the category name.
   */
  title?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'none') | null;
          newTab?: boolean | null;
          label: string;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quickLinks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuickContactBlock".
 */
export interface QuickContactBlock {
  /**
   * Section heading. Defaults to the category name.
   */
  title?: string | null;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quickContact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FollowUsBlock".
 */
export interface FollowUsBlock {
  /**
   * Links come from Site settings → Social.
   */
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'followUs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Dark footer columns (original: Quick Links · Quick Contact · Follow Us)
   */
  columns?:
    | {
        title: string;
        kind: 'links' | 'contact' | 'social' | 'text';
        links?:
          | {
              link: {
                type?: ('reference' | 'custom' | 'none') | null;
                newTab?: boolean | null;
                label: string;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null)
                  | ({
                      relationTo: 'categories';
                      value: string | Category;
                    } | null);
                url?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  bottomLinks?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'none') | null;
          newTab?: boolean | null;
          label: string;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteNameMl?: T;
  tagline?: T;
  logo?: T;
  partnerLogo?: T;
  partnerUrl?: T;
  defaultOgImage?: T;
  social?:
    | T
    | {
        facebook?: T;
        x?: T;
        instagram?: T;
        youtube?: T;
        whatsapp?: T;
        telegram?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  topBarLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  showSocialInTopBar?: T;
  mainMenu?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                  };
              children?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          label?: T;
                          reference?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        featuredSlider?: T | FeaturedSliderBlockSelect<T>;
        categoryFeature?: T | CategoryFeatureBlockSelect<T>;
        categoryGrid?: T | CategoryGridBlockSelect<T>;
        categoryList?: T | CategoryListBlockSelect<T>;
        mediaShelf?: T | MediaShelfBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
      };
  sidebar?:
    | T
    | {
        categoryList?: T | CategoryListBlockSelect<T>;
        quickLinks?: T | QuickLinksBlockSelect<T>;
        quickContact?: T | QuickContactBlockSelect<T>;
        followUs?: T | FollowUsBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedSliderBlock_select".
 */
export interface FeaturedSliderBlockSelect<T extends boolean = true> {
  source?: T;
  category?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryFeatureBlock_select".
 */
export interface CategoryFeatureBlockSelect<T extends boolean = true> {
  width?: T;
  category?: T;
  title?: T;
  layout?: T;
  limit?: T;
  showMoreLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock_select".
 */
export interface CategoryGridBlockSelect<T extends boolean = true> {
  width?: T;
  category?: T;
  title?: T;
  columns?: T;
  limit?: T;
  showMoreLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryListBlock_select".
 */
export interface CategoryListBlockSelect<T extends boolean = true> {
  width?: T;
  category?: T;
  title?: T;
  limit?: T;
  showThumbnails?: T;
  showMoreLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaShelfBlock_select".
 */
export interface MediaShelfBlockSelect<T extends boolean = true> {
  width?: T;
  format?: T;
  category?: T;
  title?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  width?: T;
  title?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  width?: T;
  image?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        label?: T;
        reference?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuickLinksBlock_select".
 */
export interface QuickLinksBlockSelect<T extends boolean = true> {
  title?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuickContactBlock_select".
 */
export interface QuickContactBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FollowUsBlock_select".
 */
export interface FollowUsBlockSelect<T extends boolean = true> {
  title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        kind?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    label?: T;
                    reference?: T;
                    url?: T;
                  };
              id?: T;
            };
        text?: T;
        id?: T;
      };
  bottomLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeBlock".
 */
export interface YouTubeBlock {
  url: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtube';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PdfAttachmentBlock".
 */
export interface PdfAttachmentBlock {
  file: string | Media;
  label?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pdfAttachment';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}